// <auto-generated />
using System;
using ApiProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiProject.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("FaultReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3856),
                            CreatedByUserId = 2,
                            Description = "Ofiste elektrik kesildi",
                            Location = "İstanbul",
                            Priority = 2,
                            Status = 0,
                            Title = "Elektrik Kesintisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3860),
                            CreatedByUserId = 2,
                            Description = "WiFi çalışmıyor",
                            Location = "Ankara",
                            Priority = 1,
                            Status = 1,
                            Title = "İnternet Bağlantısı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3862),
                            CreatedByUserId = 2,
                            Description = "Printer kağıt sıkıştı",
                            Location = "İzmir",
                            Priority = 0,
                            Status = 0,
                            Title = "Printer Arızası"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3863),
                            CreatedByUserId = 2,
                            Description = "Klima çalışmıyor",
                            Location = "Bursa",
                            Priority = 1,
                            Status = 2,
                            Title = "Klima Sorunu"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3864),
                            CreatedByUserId = 2,
                            Description = "Bilgisayar sürekli donuyor",
                            Location = "Antalya",
                            Priority = 2,
                            Status = 0,
                            Title = "Bilgisayar Donması"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3865),
                            CreatedByUserId = 2,
                            Description = "Ofiste su sızıntısı var",
                            Location = "İstanbul",
                            Priority = 1,
                            Status = 1,
                            Title = "Su Kaçağı"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3866),
                            CreatedByUserId = 2,
                            Description = "Telefon çalışmıyor",
                            Location = "Ankara",
                            Priority = 0,
                            Status = 0,
                            Title = "Telefon Hattı Sorunu"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3868),
                            CreatedByUserId = 3,
                            Description = "Projeksiyon ışığı yanmıyor",
                            Location = "İzmir",
                            Priority = 1,
                            Status = 2,
                            Title = "Projeksiyon Arızası"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3869),
                            CreatedByUserId = 3,
                            Description = "Giriş kapısı kilitlenmiyor",
                            Location = "Bursa",
                            Priority = 2,
                            Status = 0,
                            Title = "Kapı Kilidi Bozuk"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3870),
                            CreatedByUserId = 3,
                            Description = "Ağ bağlantısı çok yavaş",
                            Location = "Antalya",
                            Priority = 0,
                            Status = 1,
                            Title = "Internet Yavaşlığı"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3871),
                            CreatedByUserId = 3,
                            Description = "Acil durum ışığı yanmıyor",
                            Location = "İstanbul",
                            Priority = 2,
                            Status = 4,
                            Title = "Acil Durum Işığı"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 31, 10, 17, 43, 825, DateTimeKind.Utc).AddTicks(3872),
                            CreatedByUserId = 1,
                            Description = "Bu arıza Admin tarafından açıldı",
                            Location = "İstanbul",
                            Priority = 2,
                            Status = 0,
                            Title = "Admin Test Arızası"
                        });
                });

            modelBuilder.Entity("ApiProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456",
                            Role = "Admin",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123456",
                            Role = "User",
                            UserName = "TestUser1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "123456",
                            Role = "User",
                            UserName = "TestUser2"
                        });
                });

            modelBuilder.Entity("ApiProject.Models.FaultReport", b =>
                {
                    b.HasOne("ApiProject.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
